# -*- coding: utf-8 -*-
"""JormadaFaixaPretaPython3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVbsIKK5B8-jZsVmRhD4hI8k7ZwYMstw

# Condicionais

Principal forma de atribuir uma logica ao seu codigo.
Basicamente é uma tomada de decisão caso a condição seja verdadeira.

Ex:

- Se o dia estiver quente:
  - Vou tomar um sorvete
  -Vou para a praia

- Do contrario (se não):
  - Comer um chocolate
  - Maratonar netflix
"""

temperatura = "frio"
print(temperatura)

if temperatura =="quente":
  print("Vou tomar um sorvete de flocos")
  print("Vou para a praia")

else:
  print("Vou comer um chocolate")
  print("Vamos assistir Peaky Blinders")

horario = "Noite"

if horario == "manhã":
  print("O sol está quente")
elif horario == "tarde":
  print("O por de sol está chegando")
else:
  print("A lua está linda")
  print("Está na hora de programar hentai")

idade = 14

if idade >= 18:
  print("Você já pode beber, mas com moderação!")
else:
  print("Você não pode beber!")

temperatura = 37

if temperatura <= 30:
  print("Aceitavel")
else:
  print("Socorro está muito quente")

altura = 1.82

if altura > 1.80:
  print("O xablau é gigante")
else:
  print("O xablau é nanico")

quente = False
gosta_praia = False
gosta_chocolate_quente = True

if quente == True:
  print("Está quente")
  if gosta_praia == True:
    print("Vá para a praia")
  else:
    print("Não vá a praia")
else:
  print("Está frio")
  if gosta_chocolate_quente == True:
    print("Tome um chocolate quente")
  else:
    print("Não tome chocolate quente")

dia = input("Qual é o dia atual? ")

if dia == "sabado":
  print("É fim de semana :D")
elif dia == "domingo":
  print("É fim de semana :D")
else:
  print("Não é fim de semana :(")

# 1, 3, 6 e 10 => valido
# qualquer outro => invalido

numero = input("Qual é o numero?")

if numero == 1 or numero == 3 or numero == 6 or numero == 10:
  print("É valido")
else:
  print("É invalido")



"""# Operadores Logicos

Servem para fazer uma condição composta

E => Ambas precisam ser verdade
Ou => Pelo menos uma precisa ser verdade

Ex:
 - Se for manhã e estiver sol
 - Se for sabado ou domingo
"""

meu_nome = "Breno"
nome = input("Digite seu nome: ")

meu_sobrenome = "Silva"
sobrenome = input("Digite seu sobrenome: ")

if nome == meu_nome and sobrenome == meu_sobrenome:
  print("Você é o Breno Silva")
else:
  print("Você não é o Breno Silva")

"""# Laços de repetição

É uma excelente forma de evitar repetição de codigo.

Ele vai execuar "n" vezes uma operação

"n" => quantidade de vezes definida.
"""

# De 1 até 10 vamos printar todos os numeros
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
# Na programação o minimo (1) é INCLUSO => Ele existe
# Ja é maximo (10) é excluso => Ele não existe

for numero in range(1,10):
  print(numero)

for numero in range(10):
  print(numero)

""""For" => palavra-chave para Repetição.
"Variavel" => O dado em que estamos trabalhando no momento
atual.
"in" => palavra-chave para "onde vamos repetir?"
"intervalo/sequencia" => Oque vamos repetir
"""

for numero in range(5):
  print(numero)

#    for        numero       in         range(5)
# para cada     numero      no         intervalo até 5

for numero in range(1,11):
  print("O numero atual é:", numero)

texto = "Não trave o zap dos amigos"

for vez in range(10):
  print(texto)

nomes = ["Breno", "Sandra", "Jo", "Ze russo"]

for nome in nomes:
  print("O nome atual é:", nome)
  if nome == "Breno":
    print("(Ou xablau)")

notas = [6, 7.5, 9, 10, 3, 5]

soma = 0

for nota in notas:
  soma = soma + nota

print("A soma é", soma)

media = soma / len(notas)

print("A media é", media)

numero_sorte = 10

numero = int(input("Escolha um numero: "))

if numero != 10:
  print("errou o numero")

"""# Função

Toda função é uma rotina.

Eu defino (def) uma rotina e a executo quantas vezes quiser.

É uma excelente forma de deixar nosso dinamico sem repetição.
"""

def nome_funcao():
  print("Codigo da função")


nome_funcao()

def mostrar_nome():
  print("Breno silva")
  print("Xablau")


mostrar_nome()

"""# Parametro/Argumento da função

É uma maneira de enviar dados para a função
"""

print("argumento")

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2
  print(media)

primeira_nota = float(input("Sua primeira nota: "))
segunda_nota = float(input("Sua segunda nota: "))

calcular_media(primeira_nota, segunda_nota)

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2
  return media

media_calculada + calcular_media(10,8)

print(media_calculada)

def numero_quadrado(numero):
  quadrado = numero * numero
  return quadrado

def calcular_imc(peso, altura):
  altura_quadrada = numero_quadrado(altura)
  meu_imc = peso / altura_quadrada

  return meu_imc

def classificar_imc(meu_imc):
  if imc < 18.5:
    print("Magreza")
  elif imc >= 18.5 and imc < 25:
    print("Normal")
  elif imc >= 25 and imc < 30:
    print("Sobrepeso")
  elif imc >= 30 and imc < 40:
    print("Obseidade")
  else:
    print("Obesidade grave")  


imc = calcular_imc(61, 1.80)
print(imc)

print("Seu IMC é: ", imc)

print("Sua classificação é: ")
classificar_imc(imc)