# -*- coding: utf-8 -*-
"""JornadaFaixaPretaAula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDdDC3iPQbAbs8IUGyD7_FY2QzM828dM

#Identação de codigo

Identação é aquele espaçamento no inicio da linha.

O nivel mais a direita pertence ao nivel mais a esquerda
"""

# Nivel Pai
  # Nivel Filho
    # Nivel Neto
      # Nivel Bisneto 1
      # Nivel Bisneto 2
      # Nivel Bisneto 3
    #Nivel Neto 2

print("ByLearners")

"""# Variáveis

Um variável um nome que se refere a um valor.

## Motivo do uso

São usadas para guardar valores para serem usadas mais tarde no programa

## Sintaxe

variavel = valor
variavel = novo_valor
novo_variavel = variavel
"""

nome = "Breno"
idade = 14

nome

idade

idade = idade + 1

idade

idade_breno_2021 = idade

idade_breno_2021

primeiro_numero = 15
segundo_numero = 10

soma = primeiro_numero + segundo_numero

soma

nome = "Breno"
sobrenome = "Silva"
apelido = "Xablau"

nome_completo = nome + sobrenome

nome_completo

nome_completo = nome + " " + sobrenome

nome_completo

apelido

"""# Tipos de dados

Toda variavel ela tem um tipo, que a define se é um texto, numero, booleano
"""

inteiro = 10
decimal = 10.5
texto = "breno silva"
verdadeiro_falso = True

23 + 10

"23" + "10"

type(23)

type("23")

type(inteiro)

type(decimal)

type(texto)

type(verdadeiro_falso)

23 + "abc"

# int inteiros
# Float Numeros com virgula
# str strings (txt)
# bool Booleanos (verdadeiro e falso)

texto_10 = "10"
numero_20 = 20

type(texto_10)

type(numero_20)

numero_10 = int(texto_10)

type(numero_10)

texto_10 = str(numero_20)

type(texto_10)

type(numero_20)

esta_chovendo = True

esta_frio = False

"""# Operações Matemagicas

Podemos fazer todas as operaçoes matematicas facilmente

Soma +
Subtracao -
Multiplicacao *
Divisao /
"""

soma = 10 + 20

subtracao = 20 + 10

multiplicacao = 2 * 3

divisao = 8 / 2

soma

subtracao

multiplicacao

divisao

primeiro_numero = 20
segundo_numero = 30
terceiro_numero = 10
quarto_numero = 5

valor_final = (primeiro_numero + segundo_numero - terceiro_numero) / quarto_numero

valor_final

"""# Metodos de entrada

são formas de enviar valor ao python

usamos a função input()
"""

nome + input("Insira seu nome: ")

Innome

Idade = input("Insira sua idade: ")

idade

type(idade)

idade = int
input("Insira sua idade: ")

idade



"""# Metodos Saida

Mostrar um valor para o usuario.
"""

primeiro_numero = 10
segundo_numero = 20

soma = primeiro_numero + segundo_numero

print("O valor da soma é de", soma)

nome = input("Insira o seu nome: ")
idade = int(input("insira sua idade: "))

print("O", nome, "tem", idade, "anos")

print("Seja bem vindo a minha calculadora de multiplicação!")

valor1 = float(input("Insira o seu Primeiro numero: "))
valor2 = float(input("Insira o seu segundo numero: "))

multiplicacao = valor1 * valor2

print("O resultado da multiplicação entre", valor1, "e", valor2, "é de", multiplicacao)

lista_animais = ["Cachorro", "Gato", "Coelho", "Furão", "Pássaro", "Peixe"]
# Posição            1         2        3         4         5         6
# Indice             0         1        2         3         4         5

furao = lista_animais[3]
gato = lista_animais[1]

print("A shura é uma", furao)
print("O Doctor é um", gato)

